# Describes the format for available Pura services

start_timer:
  target:
    device:
      - integration: pura
        model: Pura 3
      - integration: pura
        model: Pura 4
      - integration: pura
        model: Pura Plus
      - integration: pura
        model: Pura Mini
    entity:
      - integration: pura
  fields:
    slot:
      required: false
      example: 1
      selector:
        select:
          options:
            - "1"
            - "2"
    intensity:
      required: true
      example: 4
      default: 4
      selector:
        number:
          min: 1
          max: 10
    duration:
      required: true
      example: "hours: 0\nminutes: 30\nseconds: 0"
      default:
        hours: 0
        minutes: 30
        seconds: 0
      selector:
        duration:
